import { Router } from 'express';
import contactoEmergencia from "./contactoEmergencia";
import correoIntegrante from "./correoIntegrante";
import direccionPersona from "./direccionPersona";
import eps from "./eps";
import funcionario from "./funcionario";
import integrante from "./integranteHogar";
import item from "./itemPacienteMedicamentos";
import laboratorio from "./laboratorio";
import medicamento from "./medicamento";
import medicamentoLaboratorio from "./medicamentoLaboratorio";
import paciente from "./paciente";
import controles from "./pacienteControles";
import persona from "./persona";
import registro from "./procesoRegistro";
import profesional from "./profesionalSalud";
import dosis from "./registroDosis";
import relacion from "./relacionPacienteIntegrante";
import telefonoLaboratorio from "./telefonoLaboratorio";
import personaTelefonos from "./telefonoPersona";
import tipoContacto from "./tipoContacto";
import tipoIdentificacion from "./tipoIdentificacion";
import tipoTelefono from "./tipoTelefono";
import universidad from "./universidad";
import ciudad from "./ciudad";
import pais from "./pais";
import departamento from "./departamento";
const routes = Router();

//Rutas
routes.use('/tipo-identificacion', tipoIdentificacion);
routes.use('/universidad', universidad);
routes.use('/tipo-telefono', tipoTelefono);
routes.use('/EPS', eps);
routes.use('/medicamento', medicamento);
routes.use('/tipo-contacto', tipoContacto);
routes.use('/laboratorio', laboratorio);
routes.use('/tel-laboratorio', telefonoLaboratorio);
routes.use('/persona', persona);
routes.use('/funcionario',funcionario);
routes.use('/tel-persona',personaTelefonos);
routes.use('/dir-persona',direccionPersona);
routes.use('/med-lab',medicamentoLaboratorio);
routes.use('/integranteH',integrante);
routes.use('/profesional-salud',profesional);
routes.use('/paciente',paciente);
routes.use('/relacion',relacion);
routes.use('/correo',correoIntegrante);
routes.use('/contactoEmergencia',contactoEmergencia);
routes.use('/controles',controles);
routes.use('/items',item);
routes.use('/dosis',dosis);
routes.use('/registro_info',registro);
routes.use('/ciudad',ciudad);
routes.use('/pais',pais);
routes.use('/departamento',departamento);
export default routes;